### ISSUE TITLE
Titles in the layout state of an Original Livesplit layout are no longer calculated correctly.

### ISSUE THREAD

**Issue by Ynscription** [LiveSplit/livesplit-core#314] opened 2020-03-12 15:00 UTC
After switching from the crates.io build (livesplit-core = "0.11.0") to using the master branch in git, the title of a run is no longer properly calculated when calling Layout.state on a layout from the original livesplit with **SingleLine=True**.

These are the layouts used for this report.
[Layouts.zip](https://github.com/LiveSplit/livesplit-core/files/4324826/Layouts.zip)

## Screenshots
Taken in one.livesplit.org
Both use the same run
![LiveSplitCore Layout Titles](https://user-images.githubusercontent.com/6177465/76534096-551ce980-6479-11ea-97f1-39359ebca727.png)

## To Reproduce
Assume **old_layout** is a previously loaded **Layout** from the **old_layout.lsl** file (This layout was created on the original LiveSplit)
Assume **new_layout** is a previously loaded **Layout** from the **new_layout.ls1l** file (This layout was created on one.livesplit.org)
(Both layouts have **SingleLine=True**)
Assume **timer** is a previously initialized **SharedTimer** that contains a run with a game name and a category name.
```
let old_layout_state = old_layout.state(&timer.read());
let new_layout_state = new_layout.state(&timer.read());
for component in &old_layout_state.components {
    match component {
        ComponentState::Title(old_state) => {
			for component in &new_layout_state.components {
				match component {
					ComponentState::Title(new_state) => {
						if old_state.line1.len() > 0 && new_state.line1.len() > 0 {
							let old_line1 = &old_state.line1[old_state.line1.len() - 1];
							let old_line1 = &old_line1[..];
							let new_line1 = &new_state.line1[new_state.line1.len() - 1];
							let new_line1 = &new_line1[..];
							assert_eq!(old_line1, new_line1);
						}
						else {
							assert_eq!(old_state.line1.len(), new_state.line1.len());
						}
					}
				}
			}
        },
        _ => (),
    }
}
```

## Notes
This issue did not happen when using crates.io build (livesplit-core = "0.11.0")

**Comment by CryZe** [comment] 2020-03-12 15:51
The single line title wasn't calculated properly until recently where we properly implemented abbreviations. So it is to be expected that the behavior changed. It should be the same as how the original LiveSplit does it. So I'm not sure if I'm missing something here, but this is basically "not a bug" and instead a bugfix, unless it behaves differently from the original, which would be a bug.

**Comment by CryZe** [comment] 2020-03-12 15:54
Oh wait, I see what you are saying now. This is the same livesplit-core build, but the title is behaving differently.

**Comment by CryZe** [comment] 2020-03-12 16:21
Turns out it's not really a bug. The layout from the original LiveSplit is configured to not show the game name:
```xml
 <Path>LiveSplit.Title.dll</Path>
      <Settings>
        <Version>1.7</Version>
        <ShowGameName>False</ShowGameName>
        <ShowCategoryName>True</ShowCategoryName>
```
and the new one is:
```json
                "show_game_name": true,
                "show_category_name": true,
```
However this uncovered a related bug to this. So I opened a PR that fixes it.

**Comment by Ynscription** [comment] 2020-03-12 16:43
After further investigation it turns out that it had nothing to do with the single line, the problem comes from the layout:
![LiveSplitCore Layout Title](https://user-images.githubusercontent.com/6177465/76544476-68838100-6488-11ea-8769-4b20748c8894.png)

**Comment by CryZe** [comment] 2020-03-12 16:43
So are you saying you are still seeing some bug or is it fixed with my PR? (The undefined is what gets fixed by the PR)

**Comment by CryZe** [comment] 2020-03-12 16:45
The difference you are seeing between top and bottom is that one has "Show Game Name" active and the other doesn't.

**Comment by Ynscription** [comment] 2020-03-12 16:47
Ah, that was it, I didn't notice, my bad.
What threw me off was that in the original LiveSplit it did show the name even if ShowGameName was set to False.

**Comment by Ynscription** [comment] 2020-03-12 16:50
Okay, so I was using a 2 year old version of LiveSplit, the new one doesn't show the name if ShowGameName is set to False. 🤦‍♂

**Closed** 2020-03-12 17:31 UTC
Labels: bug, suitable for contributions
