### ISSUE TITLE
Curly bracket in comment breaks auto-splitter code

### ISSUE THREAD

**Issue by Gyoshi** [LiveSplit/livesplit-core#620] opened 2022-12-27 08:52 UTC
```Csharp
startup {
	vars.test = 5;
	// this -> {
}

init {
}
```
The above code gives 'startup' method compilation errors due to the curly bracket in the commented-out line. Can lead to a pretty frustrating debugging experience when you don't expect comments to affect anything

**Comment by Jujstme** [comment] 2022-12-27 08:53
Duplicate of https://github.com/LiveSplit/LiveSplit.ScriptableAutoSplit/issues/55

**Comment by CryZe** [comment] 2022-12-28 18:04
This is the wrong repository, thus I'm closing this.

**Closed by CryZe** 2022-12-28 18:04 UTC
